# This is the config file for keyd, which usually lives in /etc/keyd/device.conf

# vim: foldmethod=marker

## Help
# sudo keyd -m (to find ID of keyboard)
# keyd list-keys
# sudo keyd monitor
## Enable for the first time
# sudo systemctl enable --now keyd
## Reload after changing config (either of these)
# sudo keyd reload
# sudo systemctl restart keyd
#
# See also:
# https://man.archlinux.org/man/extra/keyd/keyd.1.en

# NOTE: When this machine is a remote, Synergy appears to bypass keyd, so we cannot remap the keystrokes it sends us :-(

# For all keyboards
[ids]
*

[main]
shift = layer(shift)
control = layer(control)
meta = layer(meta)
leftalt = layer(alt)
rightalt = layer(altgr)

#v = b

[meta]
up = pageup
down = pagedown
i = up
j = left
k = down
l = right
# Defined globally so this mapping happens BEFORE we send the keys over Synergy to the MacBook
# Otherwise it receives Opt-[ and Opt-] but they don't go through Karabiner, so the MacBook just presses " and '
[ = macro(C-b p)
] = macro(C-b n)
# Also putting it on these for now, because I keep pressing them by accident
# Let's see later what my fingers actually gravitate towards
# NO WE MUSTN'T DO THAT because Opt-Left and Opt-Right already map to Home and End
#left = macro(C-b p)
#right = macro(C-b n)

[alt]
# Overriding the key from sxhkd (which is unreliable)
# TODO: Let's move as much as we can from sxhkd to here
# WARN: Do not add here, because they will also remap what is passed over Synergy to other machines.
#       Instead, edit app.conf and whitelist specific apps.
#v = S-insert
#r = C-r
#r = macro(leftalt-release C-r)
a = C-a

[control+alt]
a = C-A-a
b = C-A-b
c = C-A-c
d = C-A-d
e = C-A-e
f = C-A-f
g = C-A-g
h = C-A-h
i = C-A-i
j = C-A-j
k = C-A-k
l = C-A-l
m = C-A-m
n = C-A-n
o = C-A-o
p = C-A-p
q = C-A-q
r = C-A-r
s = C-A-s
t = C-A-t
u = C-A-u
v = C-A-v
w = C-A-w
x = C-A-x
y = C-A-y
z = C-A-z

[meta+alt]
# Restore what we messed up above
up = A-M-up
down = A-M-down
#i = A-M-i
#j = A-M-j
#k = A-M-k
#l = A-M-l
a = A-M-a
b = A-M-b
c = A-M-c
d = A-M-d
e = A-M-e
f = A-M-f
g = A-M-g
h = A-M-h
i = A-M-i
j = A-M-j
k = A-M-k
l = A-M-l
m = A-M-m
n = A-M-n
o = A-M-o
p = A-M-p
q = A-M-q
r = A-M-r
s = A-M-s
t = A-M-t
u = A-M-u
v = A-M-v
w = A-M-w
x = A-M-x
y = A-M-y
z = A-M-z
# Enable this if you need it
#r = A-M-r

[control+shift]
# These work on Linux, but the [ doesn't work when Synergy sends it to the MacBook
[ = macro(C-b p)
] = macro(C-b n)

[control+shift+alt]
# These work on Linux, but the [ doesn't work when Synergy sends it to the MacBook
[ = macro(C-b p)
] = macro(C-b n)
tab = macro(C-b tab)
