:include all.conf

# For Keychron K3 Pro {{{
# It was 3434:0280 but the second number can change after a hard-reset
[ids]
0fac:0ade

[main]
pageup = home
pagedown = pageup
home = pagedown

[meta]
#left = home
#right = end
left = C-left
right = C-right
