# For Keychron K3 Pro {{{
# It was 3434:0280 but the second number can change after a hard-reset
[ids]
3434

[main]
shift = layer(shift)
control = layer(control)
meta = layer(meta)
leftalt = layer(alt)
rightalt = layer(altgr)

pageup = home
pagedown = pageup
home = pagedown
